# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.14'
    windows:
      imageName: 'vs2017-win2016'

trigger:
- master

pr:
- master

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

# Linux and macOS
- script: ./fake.sh build -t Test
  condition: or( eq( variables['Agent.OS'], 'Linux' ), eq( variables['Agent.OS'], 'Darwin' ) )
  displayName: 'Run FAKE - Test'
# Windows
- script: fake.cmd build -t Test
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'Run FAKE - Test'
